version: "3"
services:
  web:
    env_file:
      - ${ENV_FILE:-.env}
    build:
      context: "."
    command: "./entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - "net"

volumes:
  redis: {}

networks:
  net:
